# Project information
site_name: yolov5.js
site_url: https://skalskip.github.io/yolov5js
site_author: Piotr Skalski
site_description: >-
  Effortless YOLOv5 JavaScript integration.
# Repository
repo_name: 'SkalskiP/yolov5js'
repo_url: 'https://github.com/SkalskiP/yolov5js'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Piotr Skalski

# Customization
extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SkalskiP
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PiotrSkalski92
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/piotr-skalski-36b5b4122/

# Page tree
nav:
  - Overview: index.md
  - Docs: api.md
  - Custom weights: weights.md

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'https://yolov5js-images.s3.eu-central-1.amazonaws.com/yolov5js-logo.png'
  favicon: 'https://yolov5js-images.s3.eu-central-1.amazonaws.com/yolov5js-logo.png'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Google Analytics
google_analytics:
  - 'UA-216477413-1'
  - 'auto'

# Extensions
markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
